# Generated by Django 4.0.3 on 2022-07-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Venue name')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('zip_code', models.CharField(max_length=10, verbose_name='zip code')),
                ('phone', models.CharField(max_length=12, verbose_name='Contact Phone')),
                ('web', models.URLField(verbose_name='Website address')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('event_name', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=100, verbose_name='Event Manager')),
                ('description', models.TextField(blank=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
                ('visitors', models.ManyToManyField(blank=True, to='events.clubuser')),
            ],
        ),
    ]
