# Generated by Django 4.0.3 on 2022-07-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_venue_email_address_alter_venue_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='venue owner'),
        ),
    ]
